# Numpy Essentials - Practical Excercises

    1. Array Creating and Basics
    2. Indexing and Slicing
    3. Vectorized Operations
    4. Broadcasting
    5. Reshaping and Cobining Arrays
    6. Conditionla Logic
    7. Aggregations & Axis
    8. File Operations

### Numpy Basics

#### Numpy and why it faster than lists

    Numpy array are provided by Numpy libraries - 
    fixed type of elements (same data type) e.g. int, float, 
    memory efficient as stored in contagious blocks and high performance like vectorized operations. 
    
    Contiguous memory means that all elements of the array are stored sequentially in memory, one after the other — 
    like rooms lined up in a straight hallway. Hence it is faster than lists (store pointer to objects)

#### Creating array - array, zeros, ones, arange, linspace

    1. np.array-create an np.array ----> Conversion from other Python structures (i.e. lists and tuples)
    2. Intrinsic NumPy array creation functions
    empty-new array w/o init, 
    ones-new array with 1's , same for zeros
    eye-2d array with 1 on diagonal only, 
    identity-square array with 1 on middle diagonal, 
    emply_like - new array from given array, 
    ones_like - new array from given array with 1's, same for zeros_like, 
    full-create a new array with the given input value, same for full_like, 
     

In [13]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [15]:
a=[1,2,3,4]
np.asarray(a)

array([1, 2, 3, 4])

In [17]:
b=[[4,5,6],[5,6,7]]
np.ndim(b)

2

In [19]:
np.shape([[1,2,4],[2,3,4]])

(2, 3)

In [20]:
np.size([[1,2],[2,3,4]])

2

In [21]:
np.arange(6).reshape((2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
x=np.arange(6).reshape((2,3))
np.ravel(x)

array([0, 1, 2, 3, 4, 5])

In [2]:
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
import numpy as np
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [4]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [5]:
x=np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [6]:
y=np.zeros_like(x)
y

array([0, 0, 0, 0, 0, 0])

In [28]:
y=np.ones_like(x)
y

array([[1, 1, 1],
       [1, 1, 1]])

In [7]:
np.full((4, 2), [1, 2])

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [11]:
f=np.full_like(x, 1)
f

array([1, 1, 1, 1, 1, 1])

In [27]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [25]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
z=np.copy(x)
z

array([[0, 1, 2],
       [3, 4, 5]])

In [2]:
import numpy as np
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

#### dtype --> int, float, string

#### Shape and size (shape, ndim, size)

In [25]:
import numpy as np
np.ndim([[1,2,3],[4,5,6]])

2

In [26]:
np.ndim(np.array([[1,2,3],[4,5,6]]))

2

In [27]:
np.ndim(1)

0

In [28]:
import numpy as np
np.shape(np.eye(3))

(3, 3)

In [29]:
np.shape([[1, 3]])

(1, 2)

In [30]:
np.shape([0])

(1,)

In [31]:
np.shape(0)

()

In [32]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
np.size(a)

6

In [33]:
np.size(a,axis=1)

3

In [34]:
np.size(a,axis=0)

2

### Indexing and Slicing

#### 1d Indexing

In [3]:
x = np.arange(10)
x[2]

2

In [4]:
x.shape = (2, 5)  # now x is 2-dimensional
x[1, 3]

8

#### 2d Indexing

In [27]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
mat[0]



array([1, 2, 3])

In [26]:
mat[1,2]

6

In [28]:
mat[:,1]

array([2, 5, 8])

#### Slicing arrays

In [5]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]

array([1, 3, 5])

In [6]:
x[5:]

array([5, 6, 7, 8, 9])

In [7]:
x[-2:10]

array([8, 9])

In [9]:
x = np.arange(10, 1, -1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

#### Boolean indexing

In [12]:
x = np.array([1., -1., -2., 3])
x[x < 0] += 20
x

array([ 1., 19., 18.,  3.])

In [13]:
x = np.arange(35).reshape(5, 7)
b = x > 20
b[:, 5]

array([False, False, False,  True,  True])

In [14]:
x[b[:, 5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [15]:
x = np.zeros((2, 2), dtype=[('a', np.int32), ('b', np.float64, (3, 3))])
x['a'].shape

(2, 2)

In [17]:
x = np.arange(10)
x[2:7] = 1
x

array([0, 1, 1, 1, 1, 1, 1, 7, 8, 9])

In [18]:
x = np.arange(10, 1, -1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [19]:
x[np.array([3, 3, 1, 8])]

array([7, 7, 9, 2])

#### Fancy Indexing

In [20]:
import numpy as np

# create a numpy array
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# select elements at index 1, 2, 5, 7
select_elements = array1[[1, 2, 5, 7]]

print(select_elements)

[2 3 6 8]


In [21]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# select a single element
simple_indexing = array1[3]

print("Simple Indexing:",simple_indexing)   # 4

# select multiple elements
fancy_indexing = array1[[1, 2, 5, 7]]

print("Fancy Indexing:",fancy_indexing)   # [2 3 6 8]

Simple Indexing: 4
Fancy Indexing: [2 3 6 8]


In [22]:
import numpy as np

array1 = np.array([3, 2, 6, 1, 8, 5, 7, 4])

# sort array1 using fancy indexing
sorted_array = array1[np.argsort(array1)]

print(sorted_array)

# Output: [1, 2, 3, 4, 5, 6, 7, 8]

[1 2 3 4 5 6 7 8]


In [23]:
import numpy as np

array1 = np.array([3, 2, 6, 1, 8, 5, 7, 4])

# create a list of indices to assign new values
indices = [1, 3, 6]

# create a new array of values to assign
new_values = [10, 20, 30]

# use fancy indexing to assign new values to specific elements
array1[indices] = new_values

print(array1)

# Output: [ 3 10  6 20  8  5 30  4]

[ 3 10  6 20  8  5 30  4]


In [24]:
import numpy as np

# create a 2D array
array1 = np.array([[1, 3, 5], 
                [11, 7, 9], 
                [13, 18, 29]])

# create an array of row indices
row_indices = np.array([0, 2])

# use fancy indexing to select specific rows
selected_rows = array1[row_indices, :]

print(selected_rows)

[[ 1  3  5]
 [13 18 29]]


### Vectorized Operations 

#### arithemetic operations on arrays

In [44]:
np.add([1,2,3],[5,])

array([6, 7, 8])

In [43]:
np.subtract(4.0, 2.0)

2.0

In [39]:
np.multiply(2.0, 4.0)

8.0

In [40]:
np.divide(8.0, 3.0)

2.6666666666666665

In [41]:
np.power(2.0, 3.0)

8.0

In [59]:
np.sqrt([8.0,9,4])

array([2.82842712, 3.        , 2.        ])

In [60]:
np.square([8.0,9,4])

array([64., 81., 16.])

#### comparison operations 

In [70]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [72]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])
np.array_equal(a, c)

True

#### mathematical functions (sum, min, max, mean, std)

In [50]:
import numpy as np
a = np.arange(8)
a


array([0, 1, 2, 3, 4, 5, 6, 7])

In [51]:
np.min(a)

0

In [52]:
np.max(a)

7

In [53]:
np.sum(a)

28

In [54]:
np.mean(a)

3.5

In [55]:
np.std(a)

2.29128784747792

#### element wise operations

In [73]:
a = np.array([1, 2, 3, 4])
a + 1

array([2, 3, 4, 5])

In [74]:
2**a

array([ 2,  4,  8, 16], dtype=int32)

In [75]:
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [76]:
a * b

array([2., 4., 6., 8.])

In [78]:
j = np.arange(5)
2**(j + 1) - j

array([ 2,  3,  6, 13, 28])

In [80]:
c = np.ones((3, 3))
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

### Broadcasting 

    It shows how NumPy treats arrays with different shapes during arithmetic operations. 
    Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible  shapes.

    When operating on two arrays, NumPy compares their shapes element-wise. 
    It starts with the trailing (i.e. rightmost) dimension and works its way left. 
    Two dimensions are compatible when they are equal, or one of them is 1.

In [31]:
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [38]:
import numpy as np
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)
c=x+y
print(c)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


### Reshaping and combining arrays

#### reshape

In [47]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [49]:
np.reshape(a, (3,-1))   # the unspecified value is inferred to be 2

array([[1, 2],
       [3, 4],
       [5, 6]])

#### ravel, flatten

In [38]:
#ravel - Return a contiguous flattened array.
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [40]:
x.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [42]:
#Flatten () is comparatively slower than ravel () as it occupies memory. 
#Ravel is a library-level function. Flatten is a method of an ndarray object.
import numpy as np
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

#### concatenate, stack, vstack, hstack

    stack - Join a sequence of arrays along a new axis
    concatenate - Join a sequence of arrays along an existing axis
    vstack - Stack arrays in sequence vertically (row wise)
    dstack - Stack arrays in sequence depth wise (along third axis)
    hstack - Stack arrays in sequence horizontally (column wise)

In [43]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [45]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

In [50]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
import numpy as np
a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [52]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [54]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
import numpy as np
a = np.array((1,2,3))
b = np.array((4,5,6))
np.dstack((a,b))

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [56]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.dstack((a,b))

array([[[1, 4]],

       [[2, 5]],

       [[3, 6]]])

#### Transpose(T)

In [32]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
np.transpose(a)

array([[1, 3],
       [2, 4]])

### Conditional logic with Numpy

#### where 

In [67]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.where(a < 5, a, 10*a)    #Return elements chosen from x or y depending on condition.

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [69]:
a = np.array([[0, 1, 2],
              [0, 2, 4],
              [0, 3, 6]])
np.where(a < 4, a, -1)

array([[ 0,  1,  2],
       [ 0,  2, -1],
       [ 0,  3, -1]])

#### filtering with conditions

In [66]:
# importing numpy lib
import numpy as np

# making a numpy array
arr = np.array([x for x in range(11, 20)])

print("Original array")
print(arr)

# defining mask
mask = [True, False, True, False, True, True, False, False, False]

# making new array on conditions
new_arr = arr[mask]

print("New array")
print(new_arr)

Original array
[11 12 13 14 15 16 17 18 19]
New array
[11 13 15 16]


#### masking values 

In [65]:
#An array class with possibly masked values.
#Masked values of True exclude the corresponding element from any computation.
data = np.arange(6).reshape((2, 3))
np.ma.MaskedArray(data, mask=[[False, True, False],
                              [False, False, True]])

masked_array(
  data=[[0, --, 2],
        [3, 4, --]],
  mask=[[False,  True, False],
        [False, False,  True]],
  fill_value=999999)

### Aggregations and Axis understanding

#### sum, mean with axis=0 and axis=1 

In [57]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
np.mean(a)

2.5

In [58]:
np.mean(a, axis=0)

array([2., 3.])

In [59]:
np.mean(a, axis=1)

array([1.5, 3.5])

In [60]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
np.std(a)

1.118033988749895

In [61]:
import numpy as np
np.sum([0.5, 1.5])

2.0

In [62]:
np.sum([0.5, 0.7, 0.2, 1.5], dtype=np.int32)

1

In [63]:
np.sum([[0, 1], [0, 5]], axis=0)

array([0, 6])

In [64]:
np.sum([[0, 1], [0, 5]], axis=1)

array([1, 5])

#### differences between row-wise and column-wise operations

#####  axis = 0 ---> row-wise and axis=1 ----> column-wise operations

### Numpy + Files 

#### load data using loadtxt, genfromtxt 

In [18]:
#load - Store data to disk, and load it again
np.save('some_file', np.array([[1, 2, 3], [4, 5, 6]]))
np.load('some_file.npy')

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
from io import StringIO   # StringIO behaves like a file object
d = StringIO("1 2\n2 4\n3 9 12\n4 16 20")
np.loadtxt(d, usecols=(0, 1))

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  9.],
       [ 4., 16.]])

In [23]:
c = StringIO("0 1\n2 3")
np.loadtxt(c)

array([[0., 1.],
       [2., 3.]])

In [24]:
#genfromtxt - Load data from a text file, with missing values handled as specified.
s = StringIO("1,1.3,abcde")
data = np.genfromtxt(s, dtype=[('myint','i8'),('myfloat','f8'),
('mystring','S5')], delimiter=",")
data

array((1, 1.3, b'abcde'),
      dtype=[('myint', '<i8'), ('myfloat', '<f8'), ('mystring', 'S5')])

#### save arrays using save, savetxt 

In [7]:
import numpy as np

In [8]:
from tempfile import TemporaryFile
outfile = TemporaryFile()
print(outfile)

In [9]:
x = np.arange(10)
np.save(outfile, x)

In [10]:
_ = outfile.seek(0)
np.load(outfile)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
with open('test.npy', 'wb') as f:
    np.save(f, np.array([1, 2]))
    np.save(f, np.array([1, 3]))
with open('test.npy', 'rb') as f:
    a = np.load(f)
    b = np.load(f)
print(a, b)

[1 2] [1 3]


In [13]:
import numpy as np
from tempfile import TemporaryFile
outfile = TemporaryFile()
x = np.arange(10)
y = np.sin(x)
np.savez(outfile, x, y)
_ = outfile.seek(0) # Only needed to simulate closing & reopening file
npzfile = np.load(outfile)
npzfile.files

['arr_0', 'arr_1']

In [14]:
npzfile['arr_0']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
npzfile['arr_1']

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [16]:
#savetxt - Save an array to a text file
import numpy as np
x = y = z = np.arange(0.0,5.0,1.0)
np.savetxt('test.out', x, delimiter=',')   # X is an array
np.savetxt('test.out', (x,y,z))   # x,y,z equal sized 1D arrays
np.savetxt('test.out', x, fmt='%1.4e')   # use exponential notation